# Generated by Django 3.0.4 on 2020-03-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miniurl',
            options={'verbose_name': 'Mini URL', 'verbose_name_plural': 'Minis URLs'},
        ),
    ]
