# Generated by Django 3.0.4 on 2020-03-20 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout du document")),
                ('auteur', models.CharField(blank=True, max_length=255, null=True)),
                ('contenu', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout du document")),
                ('auteur', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('lieu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Lieu')),
                ('menu', models.TextField()),
            ],
            bases=('blog.lieu',),
        ),
    ]
