# Generated by Django 3.0.4 on 2020-03-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
