# Generated by Django 3.0.4 on 2020-03-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date'], 'permissions': (('commenter_article', 'Commenter un article'), ('marquer_article', 'Marquer un article comme lu'))},
        ),
    ]
